set nocompatible              " be iMproved, required
filetype off                  " required

let mapleader=","
runtime plugins.vim
runtime mappings.vim

" C-k invoke digraphs inserting
digraphs sr 128156   " 💜
digraphs CA 769      "  ́

" turn on czech by f7, off by f8
nnoremap <F7> set keymap=czech<CR>
nnoremap <F8> :set keymap=<CR>
inoremap <F7> <C-o>:set keymap=czech<CR>
inoremap <F8> <C-o>:set keymap=<CR>

" let g:python_host_prog = expand('~/.pyenv/versions/neovim2/bin/python')
" let g:python3_host_prog = expand('~/.pyenv/versions/neovim3/bin/python')

" let g:python_host_prog = "/usr/bin/python2"
" let g:python3_host_prog = "/usr/local/bin/python3"
let g:python3_host_prog = "/opt/homebrew/bin/python3"

set laststatus=2
let g:airline_powerline_fonts = 1
set nofoldenable

filetype plugin indent on    " required

" augroup fmt
"   autocmd!
"   autocmd BufWritePre * undojoin | Neoformat
" augroup END
nnoremap - :Neoformat<cr>

autocmd FileType javascript setlocal makeprg=eslint\ --format\ compact

" Typescrupt:
autocmd BufNewFile,BufRead *.tsx,*.jsx set filetype=typescript.tsx

syntax enable " Turn on syntax highlighting
set history=1000 " By default Vim saves your last 8 commands
set number " Set the line numbers
set encoding=utf-8
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set hidden

" Note that the dot is a unicode character
set list lcs=trail:·,tab:»·,trail:·
set hlsearch
set incsearch
set ignorecase
set smartcase

set backupcopy=yes

set backupdir=~/.vim/backup
set directory=~/.vim/backup

set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*,node_modules,tmp,project/target,target,tags,CMakeFiles,bower_components,dist,_darcs,vcr,app/assets/images,*.dSYM,*.pyc,_build,deps,rel,target,*.rpyc

set t_Co=256
set bg=dark
let base16colorspace=256  " Access colors present in 256 colorspace
color base16-nord

" Remember last location in file
aug last_location
  au!
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
    \| exe "normal g'\"" | endif
aug END

" Save undo history
if has('persistent_undo')
  set undofile
  if !isdirectory(expand('~/.vimundo'))
    silent !mkdir ~/.vimundo > /dev/null 2>&1
  endif
  set undodir=~/.vimundo
endif

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" Show (partial) command in the status line
set showcmd
set cursorline
set tags+=gems.tags

aug various_file_types
  au!
  " Rakefile, Vagrantfile and Gemfile are Ruby
  au BufRead,BufNewFile {Capfile,Gemfile,Rakefile,Vagrantfile,config.ru} set ft=ruby
  au BufNewFile,BufRead *.json set filetype=javascript
  au BufNewFile,BufRead *.slime set filetype=slim
  au BufNewFile,BufRead *.conf set filetype=conf
  au BufNewFile,BufRead *vimrc set filetype=vim
aug END

set pastetoggle=<F3>

autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

set mouse=a
set exrc
set secure

" automatically rebalance windows on vim resize
autocmd VimResized * :wincmd =

"Settings for Vim Rspec plugin
let g:rspec_command = "VimuxRunCommand 'rspec {spec}'"

command W w

if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif












" Better display for messages
" set cmdheight=2

" You will have bad experience for diagnostic messages when it's default 4000.
set updatetime=300

" don't give |ins-completion-menu| messages.
set shortmess+=c

" always show signcolumns
" set signcolumn=yes

" Use tab for trigger completion with characters ahead and navigate.
" Use command ':verbose imap <tab>' to make sure tab is not mapped by other plugin.





" nmap <C-i> iimport ipdb; ipdb.set_trace()<C-c>
" imap <C-i> import ipdb; ipdb.set_trace()<C-c>

